#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# app/config/routes.yaml
change_language:
    path: /change-language
    controller: App\Controller\HomeController::changeLanguage
